### ISSUE TITLE
Failed to load the php-checkstyle package on Atom start-up

### ISSUE THREAD

**Issue by jcwatson11** [benmatselby/atom-php-checkstyle#35]
I just downloaded Atom for the first time and started it up today, and got this error straight away before even seeing the welcome screen.

1. Download a fresh install of Atom for Mac.
2. You might need to remove any user preferences before you run it for the first time, since this is the first time I have installed it.
3. Start the app.

This error report came from the second time I started Atom because I thought maybe just restarting might help. The only configuration changes I made were to the projectHome directory, as you'll see in the config read-out.

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [php-checkstyle](https://github.com/benmatselby/atom-php-checkstyle) package, v0.12.0

### Stack Trace

Failed to load the php-checkstyle package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:8:3
    at Object.<anonymous> (<anonymous>:8:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:2:25)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:2:21)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/jwatson/Source",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.21.0
php-checkstyle, v0.12.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by benmatselby** [comment]
@jcwatson11 Hi Jon, as per the readme, this package is no longer supported, and hasn't for over 18 months
